package test;

/**
 *
 * @author HP
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    private int posX, posY;

    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 89, 38));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 89, 38));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(217, 153, 88));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        continueButton.setBackground(new java.awt.Color(244, 226, 133));
        continueButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        continueButton.setForeground(new java.awt.Color(51, 66, 38));
        continueButton.setText("Continue");
        continueButton.setBorder(null);
        continueButton.setBorderPainted(false);
        continueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueButton.setFocusPainted(false);
        continueButton.setFocusable(false);
        continueButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                continueButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                continueButtonMouseReleased(evt);
            }
        });
        jPanel1.add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 140, 40));

        cancelButton.setBackground(new java.awt.Color(244, 226, 133));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(51, 66, 38));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setFocusPainted(false);
        cancelButton.setFocusable(false);
        cancelButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void formMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }

    private void formMouseDragged(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int newX = getLocation().x + evt.getX() - posX;
        int newY = getLocation().y + evt.getY() - posY;

        // Set the new position of the frame
        setLocation(newX, newY);
    }

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void exitMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        exit.setForeground(new java.awt.Color(51, 89, 38));
    }

    private void continueButtonMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        continueButton.setBackground(new java.awt.Color(51,89,38));
        continueButton.setForeground(new java.awt.Color(244, 226, 133));
    }

    private void continueButtonMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        continueButton.setBackground(new java.awt.Color(244, 226, 133));
        continueButton.setForeground(new java.awt.Color(51,89,38));

    }

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        cancelButton.setBackground(new java.awt.Color(51,89,38));
        cancelButton.setForeground(new java.awt.Color(244, 226, 133));
    }

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        cancelButton.setBackground(new java.awt.Color(244, 226, 133));
        cancelButton.setForeground(new java.awt.Color(51,89,38));
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}

